// OLD VERSION OF THE LANGUAGE, IGNORE FOR NOW!!!

== Crossing the Border at Calais terminal

To take the https://en.wikipedia.org/wiki/Channel_Tunnel[Channel Tunnel] to the UK from France by vehicle, you have to pass the border crossing checkpoint.
Border crossing already happens at the country of origin, i.e., at Calais terminal.
We have to check the vehicle and its passengers fulfill all requirements.

_This is an example of an AsciiDoc rule source. Italics are explanations of the format._

=== Preamble
_Any of the following blocks can be ordered and placed where you like; they are always hoisted to the top and interpreted first. Multiple blocks of the same role are merged and an error is thrown if they disagree. Most of the time it is best to have the preamble in the master file of the rule base so we don't have duplication. It also allows sharing common types between several, independent rule bases._

==== Imports
_An import block ist used to map types referenced in the rules to types of the target language. It uses a definition list in a block with the `imports` role.
The rule language parser and compiler will decide what to do with these blocks, in the rule model this is just a map._

.Type declarations
[.imports]
====
Vehicle:: org.acme.Vehicle
Passenger:: org.acme.PersonImpl
Prompt:: org.acme.ui.UiPrompt
Date:: java.time.LocalDate
====


==== Facts

_This defines the input variables (globals) for the rule execution. They can be defined as definition lists or tables. When defined as a table, they have the fixed order of variable name, type, and optionally a description.
Facts can also objects that provide helper functions in the target model._

.Facts
[cols="1,1,3",.facts]
|===
| Fact name | Type | Description

| vehicleCrossingTheBorder | Vehicle | The vehicle that arrived at the border checkpoint.
| prompt | Prompt | Allows to ask the user for input.
| currentDate | Date | The current date.

|===

==== Outputs

_Outputs are objects that are created for the rule base execution (session). They can have an initial value. They are registered globally like facts. [] is the shorthand for collections._

.Outputs
[cols="1,1,1,3",.outputs]
|===
| Output name | Type | Initial value | Description

| rejectionReasons | String[] | [] | List of reasons the border crossing was not allowed. Empty if no problems.
| borderCrossingAllowed | Boolean | true | Whether border crossing is allowed.

|===

==== Local variables
_Local variables are the third type of globals. They are set during a rule session, but not returned to the caller._

[cols="1,1,1,3",.locals]
|===
| Variable name | Type | Initial value | Description

| alreadyAskedToDiscardDangerousItems | Boolean | false | Whether we asked the passengers to discard any dangerous items in the previous execution cycle.

|===

=== Passenger requirements

All passengers must fulfill the requirements to cross the border.

_Like all other blocks, rules can be placed freely anywhere. However, if no priority is specified, they will be ordered in source encounter order, meaning during rule firing, rules at actions at the top are executed first._

.Passengers must have valid passports
[#valid-passports,source,iskara,.rule]
----
When:
  not all $vehicleCrossingTheBorder.passengers.passport.isValid

Then:
  $rejectionReasons add: "Not all passengers have valid passports."
----


.Driver must have driver license valid in the UK
[#valid-driver-license,source,iskara,.rule]
----
When:
  not exists $vehicleCrossingTheBorder.driver.license:
    dateOfExpiry < $currentDate + 5 days,
    isInternational

Then:
  $rejectionReasons add: "Driver does not have a driver's license valid in the UK."
----

=== Vehicle requirements

Vehicles are not allowed to be overweight.

_We can reference decision tables and reference columns using placeholders. The rule compiler will decide how to best transform the rule when using a decision table. Tables can be explicitly referenced using `tableRef="id"`, but by convention, if the rule's title has exactly one cross ref to a table, we use that one (conventions like these can be disabled in the source parser)._

.Vehicles should not be overweight (using <<#vehicle-weight-limits>>)
[#vehicle-not-overweight,source,iskara,.rule-template]
----
When:
  $vehicleCrossingTheBorder.type = %Type
  $vehicleCrossingTheBorder.weight > %"Maximum Weight"

Then:
  $rejectionReasons add: ""
----

.Vehicle weight limits
[#vehicle-weight-limits]
|===
| Type  | Maximum Weight

| Car   | 1.5t
| Lorry | 5t
|===

=== Final decision

Reject border crossing if any rejection reasons present.

[#rejection-reasons-present,source,iskara,.rule]
----
When:
  exists $rejectionReasons

Then:
  $borderCrossingAllowed := false
  halt
----
